adapt 3 swift
goloveychuk/ZeroMQ pull request #16
Opened 2016-09-23 17:44 UTC by goloveychuk

2016-10-04 18:06 UTC, vovasty commented
👍

2016-10-10 08:10 UTC, botero-dev approved these changes

2016-10-10 08:10 UTC, BoteRock commented
I am no mantainer, but I'd definitely merge this =D

2016-10-10 23:17 UTC, Danappelxx requested changes
Just a few (mostly unrelated) things, overall great PR! Sorry for taking so long to review...

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Proxy.swift
> +public func proxy(_ frontend: Socket, backend: Socket, capture: Socket? = nil) {
Can we get this label back?

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Proxy.swift
>      zmq_proxy(frontend.socket, backend.socket, capture?.socket ?? nil)
I don't think this `?? nil` is necessary

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Socket.swift
> +import struct Foundation.Data
We really should be using `Axis.Buffer` instead of `Foundation.Data`...

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Socket.swift
>      public func bind(_ endpoint: String) throws {
`_` -> `to`, perhaps? sam with `connect`

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Socket.swift
`sendMessage(_:)` to `send(_:)`? That way it fits with the rest of the send methods.

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Socket.swift
>      public func receive(_ bufferSize: Int = 1024, mode: ReceiveMode = []) throws -> Data? {
This API should be `receive(into: UnsafeMutableBufferPointer<UInt8>` such as [here](https://github.com/Zewo/Zewo/blob/master/Modules/Axis/Sources/Axis/Stream/Stream.swift#L11). On a related note, `Socket` should adopt `Axis.Stream` to gain a bunch of convenience methods and be able to interact with the rest of the Zewo ecosystem.

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Socket.swift
> +        try setOption(option, value: &value, length: MemoryLayout<Int32>.stride)
I believe you can use `size` instead of `stride` here, since there's only one element.

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Socket.swift
>      func setOption(_ option: Int32, _ value: Data) throws {
Also this whole family of functions should be `set(_:to:)` IMO

2016-10-10 23:17 UTC, Danappelxx commented on Tests/MainTests/ZeroMQTests.swift
> +            while let data = try inbound.receiveString() , data != "Bye!" {
cut space before comma

2016-10-10 23:17 UTC, Danappelxx commented on Sources/Socket.swift
>      public func sendString(_ string: String, mode: SendMode = []) throws -> Bool {
Just `send` is good here - the type information is enough (following the API design guidelines). Same goes for `receiveString`

2016-10-26 14:11 UTC, BoteRock commented
Hello, I am not familiar with the Zewo project but I'm currently using ZeroMQ in swift with goloveychuk's fork.
I am no expert but I feel some changes should not be made, mainly to avoid introducing external dependencies. In my case I am using ZeroMQ for connecting a desktop and mobile app, so I wouldn't use other Zewo services and would prefer if I didn't have to include them at all.
I don't know what the Axis API does, but if you suggest  that it should be used, I think that the Axis repo would be a better place to implement this with an extension, or in ZeroMQ with the `canImport` conditional flag, so there is always a way to use ZeroMQ without depending on Axis

2016-10-26 14:14 UTC, goloveychuk commented
Yea, I agree with @BoteRock . If we can easily  avoid dependence, why we shouldn't

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Socket.swift
> +        var data = Data(count: bufferSize)
don't know what to better
count: 10 or 
capacity: 10

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Proxy.swift
> +public func proxy(_ frontend: Socket, backend: Socket, capture: Socket? = nil) {
done

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Proxy.swift
>      zmq_proxy(frontend.socket, backend.socket, capture?.socket ?? nil)
done

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Socket.swift
> +import struct Foundation.Data
I think we should avoid dependence

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Socket.swift
in zmq it's common to have send and sendMessage. Also breaking api.

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Socket.swift
>      public func bind(_ endpoint: String) throws {
it have one arg, and it's obviously what it mean. Is it needed to have named there?

2016-10-26 14:30 UTC, goloveychuk commented on Tests/MainTests/ZeroMQTests.swift
> +            while let data = try inbound.receiveString() , data != "Bye!" {
done

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Socket.swift
>      public func sendString(_ string: String, mode: SendMode = []) throws -> Bool {
done

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Socket.swift
>      func setOption(_ option: Int32, _ value: Data) throws {
internal methods, also setOption have more information what method does

2016-10-26 14:30 UTC, goloveychuk commented on Sources/Socket.swift
> +        try setOption(option, value: &value, length: MemoryLayout<Int32>.stride)
done

2016-10-26 14:30 UTC, merged

2016-10-26 14:31 UTC, goloveychuk commented
oops, I don't know why it's merged :)

2016-10-26 15:04 UTC, Danappelxx commented
@BoteRock @goloveychuk What's the issue with using Axis? It's the common code used by all zewo modules. It's not really external dependency, it doesn't bring in anything opinionated (ie libmill) - just a bunch of protocols and utilities. Without it, it's difficult to use ZeroMQ with, for example, HTTPServer (you can't do things like stream the 0mq socket to the client without a bunch of glue if you don't conform to the Stream protocol). The only thing we need out of there is buffer and stream. 

That said, I'm not entirely against having ZeroMQ be an outlier. What are your reasons for not wanting to include Axis?

@goloveychuk that's alright, this pr is pretty much ready anyway. Can you update the readme as well please?

2016-10-26 16:24 UTC, vovasty commented
@Danappelxx for this 0mq implementation Axis is not really needed. This is just a simple wrapper.

2016-10-26 22:37 UTC, Danappelxx commented
Axis is not foundation - its not a toolkit. It's just the glue for compatibility with the rest of the ecosystem. The fact that JSON and such are included in Axis is something I disagree heavily with and will be changed by the next release (0.15). Perhaps once that happens we can add it as a dependency here.

2016-10-27 10:47 UTC, goloveychuk commented
@Danappelxx I understand what you want, but zeromq is not simple socket. 
You cannot just use it as transport. It have many types of sockets, support many patterns. 
There are many limitations. E.g. you will error if will try to read from req/rep socket, while you should write to it.
If somebody want it combine with axis - it will require writing a wrapper.

2016-10-27 16:56 UTC, vovasty commented
you, guys, forgot about this one https://github.com/Zewo/Canale
this is specifically developed for Zewo & friends.